## Ngày 3 {-}


https://towardsdatascience.com/location-analytics-use-cases-that-every-data-scientist-should-know-740b708a2504

### Làm sao để xây dựng chiến lược mở rộng chi nhánh tốt nhất {-}

https://predikdata.com/how-to-create-the-best-branch-expansion-strategy/

**Location intelligence**

Location Intelligence là một kỹ thuật phân tích dữ liệu nâng cao. Nó sử dụng thông tin địa lý để khám phá các patterns, xu hướng, và mối quan hệ dựa trên dữ liệu. Kỹ thuật này khai tháng sức mạnh của thông tin địa lý để tìm insight từ dữ liệu. Bằng cách kết hợp giữa dữ liệu kinh doanh và dữ liệu không gian, Location Intelligence cung cấp những thông tin có giá trị giúp ra quyết định tốt hơn.

Có ba layer trong LI

- Layer 1: Geographical
- Layer 2: Store locations
- Layer 3: Sales data

**5 Lợi ích khi sử dụng LI**

Data-driven dicision-marking: Sử dụng dữ liệu location để đánh giá khả năng tiếp cận của một cửa hàng so với đối thủ cạnh tranh


Enhanced customer targeting : Sủ dụng location và heatmap để hiểu hành vi khách hàng https://predikdata.com/heat-maps-for-real-estate-investments/

Cải thiện lợi thế cạnh tranh:  Phân tích khả năng di chuyện và lượng người qua lại giữa 2 loại cửa hàng: https://predikdata.com/foot-traffic-in-pharmacies-cvs-pharmacy-vs-walgreens/

Tối ưu hóa chi phí

Quản lý nhân sự hợp lý


**Cách sử dụng LI cho chiến lược mở rộng chi nhánh**

- Xác định thị trường 
Sử dụng nhân khẩu học, sở thích của người tiêu dùng, hành vi mua hàng và nghiên cứu thị trường để xác định khách hàng lý tưởng của bạn. Thông tin vị trí giúp bạn tìm thấy những khu vực có lượng khách hàng tiềm năng tập trung cao, tập trung nỗ lực mở rộng vào những khu vực hứa hẹn nhất.

- Phân tích đối thủ
Đánh giá bối cảnh cạnh tranh, xác định vị trí và thị phần của đối thủ cạnh tranh. Khám phá những nhu cầu chưa được đáp ứng hoặc những khoảng trống thị trường để xác định cơ hội chi nhánh mới tại thị trường địa phương và quốc tế.

- Đánh giá khả năng tiếp cận:
Ước tính mức độ dễ dàng tiếp cận các địa điểm chi nhánh tiềm năng, bao gồm cơ sở hạ tầng giao thông, mô hình giao thông và tình trạng sẵn có của bãi đậu xe. Các trang web dễ dàng truy cập cho khách hàng và nhân viên góp phần tạo nên sự thành công của chi nhánh

- Tối ưu hóa chi phí Bất Động Sản (https://predikdata.com/heat-maps-for-real-estate-investments/)

Xác định các khu vực có giá bất động sản, giá cho thuê và quy định địa phương tối ưu bằng cách sử dụng thông tin vị trí. Cân bằng chi phí với lượng người qua lại và khả năng hiển thị cao đảm bảo lợi tức đầu tư cao, giúp bạn giảm chi phí và tăng doanh thu.

- Đánh giá lực lượng lao động địa phương
Phân tích thị trường lao động địa phương để đảm bảo có sẵn nhân viên lành nghề và đáng tin cậy. Thông tin vị trí cung cấp thông tin chi tiết về trình độ học vấn, bộ kỹ năng và mức lương trung bình, giúp bạn đưa ra quyết định nhân sự.

- Quản lý hiệu suất
Theo dõi hiệu quả hoạt động của chi nhánh mới bằng các chỉ số hiệu suất chính (KPI) và các tiêu chuẩn đã được thiết lập. Xác định các chi nhánh hoạt động kém hiệu quả và các yếu tố góp phần vào hiệu quả hoạt động của chúng để đưa ra quyết định dựa trên dữ liệu về việc cải thiện hoặc đóng cửa. Việc tích hợp chiến lược tiếp thị của bạn, bao gồm cả phương tiện truyền thông xã hội, với thông tin vị trí cho phép bạn thâm nhập các thị trường mới, nhắm mục tiêu vào các doanh nghiệp nhỏ và thúc đẩy mở rộng quốc tế. Bằng cách khai thác thông tin vị trí để mở rộng thị trường, bạn có thể cung cấp các sản phẩm hoặc dịch vụ phù hợp, tăng sức hấp dẫn đối với khách hàng tiềm năng và đảm bảo thành công lâu dài.


### Mở rộng chi nhánh sử dụng phân tích dự đoán {-}

Các bước để xác định vị trí tốt nhất cho từng điểm bán hàng

Bước 1: Thu thập dữ liệu

- Dữ liệu Demographics như: Tổng số dân, giới tính và tình trạng cư trú /Zip code
- Các yếu tố kinh thế như sales, giá nhà
- Thông tin địa lý, vị trí đối thủ cạnh tranh

Bước 2: Dự đoán doanh số cửa hàng cấp Zip -> ước tính doanh thu tiềm năng cho từng địa điểm

Bước 3: Chọn cấp ZIP có doanh số cao nhất

Bước 4: Sử dụng các mô hình để
- Hiểu các yếu tố thúc đẩy doanh số bán hàng
- Dự báo doanh thu, đồng thời nắm bắt được sức ảnh hưởng "ăn lẫn nhau" (cannibalization)
- Dự đoán nhu cầu ở cấp độ sản phẩm / phân khúc
- Tạo điểm tương đồng cho cửa hàng

Bước 5: Xác định các vị trí có thể tối ưu hóa trông qua kết hợp ví trị các cửa hàng, chi phí, tiềm năng

- Lặp lại các vị trí lưu trữ có thể có ở cấp Zip
- Giảm thiểu cannibalization bằng regression model
- Nhận diện khu vực Zip đang có lợi nhuận cao

Bước 6: Xây dựng mô hình hồi quy cấp cửa hàng

https://predikdata.com/footfall-analytics-for-site-selection-strategies/
https://predikdata.com/foot-traffic-in-pharmacies-cvs-pharmacy-vs-walgreens/


### Cannibalization Analysis (Tạm dịch phân tích ăn mòn) {-}

- https://locatium.ai/locaium-ai-blog-cannibalization-analysis/

- https://targomo.medium.com/introducing-cannibalization-analysis-examine-the-impact-of-competitors-and-network-branches-on-190e08ae002

- https://carto.com/blog/cannibalization-analysis-tutorial

- https://github.com/CarlitosDev/causalCannibalisation

Phân tích ăn mòn nhằm mục đích xác định liệu một shop mới có thu hút khách hàng khỏi những shop hiện có hay không, hay có khả năng tác động tiêu cực đến doanh thu của doanh nghiệp không, điều này rât quan trong đối với các doanh nghiệp có nhiều chi nhánh khác nhau, giúp họ đưa ra quyết định sáng suốt về địa điểm mở chi nhánh mới, di dời hoặc đóng cửa chi nhánh.

Vậy, các doanh nghiệp nào có thể tận dụng Phân tích Cannibalization

- Việc đặt một tháp 5G mới sẽ làm giảm tình trạng rời bỏ dịch vụ ở khu vực này như thế nào?
- Trạm sạc EV với sẽ có tác động lớn nhất ở đâu
- Nếu bắt đầu bán chocolate ở chi nhánh X thì nó ảnh hưởng như thế nào đến doanh số bán hàng ở chi nhánh Y


Phân tích ăn mòn có bốn bước chính

- Thu thập dữ liệu
- Xử lý dữ liệu
- Chạy phân tích ăn mòn
- Ra quyết định

#### Thu thập dữ liệu {-}

Dữ liệu cần thu thập bao gồm

- Vị trí các shop hiện có:

- Vị trí tiềm năng: Là các vị trí đặt shop có thể gây ra "ăn mòn"

Tiếp theo, chúng ta cần dữ liệu về những gì có thể thúc đấy quá trình "ăn mòn". Ví dụ

- Dân số
- Lượng khách hàng 
- Phân chồng chéo giữa 2 phần bao phủ của 2 cửa hàng
- urbanity levels: mức độ đô thị -> có thể thay bằng mật độ dân số


#### Xử lý dữ liệu

Xây dựng hàm processing

- Với mỗi địa điểm, đưa mật độ dân số vào

- Với mỗi địa điểm, tại một bán kính chỉ định, trả về vùng ảnh hưởng

#### Chạy phân tích ăn mòn

Xây dựng hàm "phân tích", kết quả trả ra các thông số như sau:

- Perc_cov_cells : là phần trăm diện tích vùng ảnh hưởng của shop mới đối với shop hiện có

- Perc_cov: là phần trăm dân số trùng lặp, 

method: STRING indicates the method of trade area generation. Three options available: buffer, kring, isoline and custom. This method applies to all locations provided.

https://academy.carto.com/advanced-spatial-analytics/spatial-analytics-for-bigquery/step-by-step-tutorials/store-cannibalization-quantifying-the-effect-of-opening-new-stores-on-your-existing-network